# Generated by Django 3.1 on 2020-08-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_auto_20200819_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='load',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pool_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
