# Generated by Django 3.1 on 2020-08-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_auto_20200820_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pool_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.pool'),
        ),
    ]
